/**
 * DO NOT EDIT THIS FILE.
 * This is a component used to check the number of renders of a slice.
 */

import { useEffect, useRef } from "react";

export function RenderCounter() {
  const renderCounter = useRef(0);
  useEffect(() => {
    renderCounter.current++;
  });
  return renderCounter.current || 1;
}
